import "~/styles/globals.css";
import "@uploadthing/react/styles.css";
import { type Metadata } from "next";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import {ClerkProvider,} from '@clerk/nextjs';
import {TopNav} from "./_components/topnav";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";

export const metadata: Metadata = {
  title: "T4 GALLERY",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};




export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body>
      <NextSSRPlugin
          routerConfig={extractRouterConfig(ourFileRouter)}
          />
        <TopNav/>
         {children}
         
        </body>
    </html>
    </ClerkProvider>
  );
}
